### ISSUE TITLE
Package Requirements Missing

### ISSUE THREAD

**Issue by gui-li** [a-lucic/cf-gnnexplainer#1]
Hi Ana,

Thanks for your work in explaining GNN in advance. It's a novel idea to interpret GNN in a counterfactual way. However, when I was trying to run your code, the environment file specified in your readme is missing. Could you please upload it for reference? The command in your readme file is `conda env create --file environment.yml`.

Best,
Gui

**Comment by a-lucic** [comment]
Done, thanks for notifying!
