### ISSUE TITLE
Explainability on cora citeseer and pubmed dataset 

### ISSUE THREAD

**Issue by abhigoku10** [a-lucic/cf-gnnexplainer#2]
@a-lucic  thanks for opensourcing the work can this be extended to opensource dataset like cora citeseer and pubmed which are used for nodeclassification task ? if so what are the code changes to be made

**Comment by a-lucic** [comment]
Hi, yes you can try any of those datasets by modifying lines 47-51 of main_explain.py:

- Replace "adj" with the adjacency matrix from one of those datasets
- Replace "features" with the feature matrix from one of those datasets
- Replace "labels" with the labels
- Adjust your train and test splits
